const LOGIN_DATA = "LOGIN_DATA";
const LOGOUT_DATA = "LOGOUT_DATA";
const HOME_DATA ="HOME_DATA"
const LIKE_POST = "LIKE_POST"
const UNLIKE_POST = "UNLIKE_POST"
export {LOGIN_DATA, HOME_DATA,LIKE_POST,UNLIKE_POST,LOGOUT_DATA}